### ISSUE TITLE
PA Review: Stories

### ISSUE THREAD

**Issue by candyapplecorn** [candyapplecorn/discourse#10]
Stories #create, #index, #show should be implemented

**Comment by candyapplecorn** [comment]
https://write-it-up.herokuapp.com/#/

**Comment by rkoeze** [comment]
Looks great! A couple of things:

1) You'll need to seed this with 10-12 stories that have more text than the current seeds. Make them look more like actual medium posts.

2) We should find a way that allows us to save image links to the database, instead of continuing to host them elsewhere even after saving. You don't have to implement this now, but keep it in mind for when you come back to this project during the job search. 

If you can address issues #1 I can check this off. Thanks!

**Comment by rkoeze** [comment]
These seeds still aren't professional enough. Fix the broken image urls and remove the lorem ipsum.

**Comment by candyapplecorn** [comment]
How about now? @rkoeze 
I've removed the lorem ipsum and have ten stories, 9 of which... yeah. I will write some more before Friday
